from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    CurrentteacherProfileView,
    CurrentteacherScheduleView,
    ReceiveQRDataTView,
    TeacherListView,
    TeacherCreateView,
    TeacherAccountUpdateView,
    TeacherDeleteView,
    TeacherDetailView,
    TeacherAccountCreateView,
    TeacherAccountDeleteView,
    TeacherAccountResetPasswordView,
    GradesListView,
    GradesCreateView,
    GradesUpdateView,
    GradesDeleteView,
    SubjectListView,
    SubjectCreateView,
    SubjectDeleteView,
    ClasseListView,
    ClasseCreateView,
    ClasseDeleteView,
    ScheduleTListView,
    ScheduleTCreateView,
    ScheduleTUpdateView,
    ScheduleTDeleteView,
    AttendanceTListView,
    AttendanceTCreateView,
    AttendanceTUpdateView,
    AttendanceTDeleteView,
    TeacherQRCodeView,
    TeacherStudentsView,
    LevelListView,
)

urlpatterns = [
    path('api/qr/receive/', ReceiveQRDataTView.as_view(), name='receive_qr_data_t'),
    path('api/teachers/list/', TeacherListView.as_view(), name='teacher_list'),
    path('api/teachers/add/', TeacherCreateView.as_view(), name='add_teacher'),
    path('api/teachers/edit/<int:pk>/', TeacherAccountUpdateView.as_view(), name='edit_teacher'),
    path('api/teachers/delete/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
    path('api/teachers/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('api/teachers/account/add/<int:teacher_id>/', TeacherAccountCreateView, name='add_teacher_account'),
    path('api/teachers/account/delete/<int:pk>/', TeacherAccountDeleteView.as_view(), name='delete_teacher_account'),
    path('api/teachers/account/reset-password/<int:pk>/', TeacherAccountResetPasswordView.as_view(), name='reset_teacher_password'),
    path('api/grades/list/', GradesListView.as_view(), name='list_grades'),
    path('api/grades/add/', GradesCreateView.as_view(), name='add_grades'),
    path('api/grades/edit/<int:grade_id>/', GradesUpdateView.as_view(), name='edit_grade'),
    path('api/grades/delete/<int:grade_id>/', GradesDeleteView.as_view(), name='delete_grade'),
    path('api/subjects/list/', SubjectListView.as_view(), name='subject_list'),
    path('api/subjects/add/', SubjectCreateView.as_view(), name='add_subject'),
    path('api/subjects/delete/<int:subject_id>/', SubjectDeleteView.as_view(), name='delete_subject'),
    path('api/classes/list/', ClasseListView.as_view(), name='classe_list'),
    path('api/classes/add/', ClasseCreateView.as_view(), name='add_classe'),
    path('api/classes/delete/<int:id>/', ClasseDeleteView.as_view(), name='classe_delete'),
    path('api/schedules/teacher/<int:teacher_id>/', ScheduleTListView.as_view(), name='schedule_list'),
    path('api/schedules/add/', ScheduleTCreateView.as_view(), name='add_schedule'),
    path('api/schedules/update/<int:schedule_id>/', ScheduleTUpdateView.as_view(), name='update_schedule'),
    path('api/schedules/delete/<int:schedule_id>/', ScheduleTDeleteView.as_view(), name='delete_schedule'),
    path('api/teacher/qrcode/<int:pk>/', TeacherQRCodeView.as_view(), name='teacher_qrcode'),
    path('api/attendance-t/list/', AttendanceTListView.as_view(), name='attendance-t-list'),
    path('api/attendance-t/create/', AttendanceTCreateView.as_view(), name='attendance-t-create'),
    path('api/attendance-t/<int:pk>/update/', AttendanceTUpdateView.as_view(), name='attendance-t-update'),
    path('api/attendance-t/<int:pk>/delete/', AttendanceTDeleteView.as_view(), name='attendance-t-delete'),
    path('api/teacher/profile/', CurrentteacherProfileView.as_view(), name='current_teacher_profile'),
    path('api/teacher/schedule/', CurrentteacherScheduleView.as_view(), name='current_teacher_schedule'),
    path('api/teachers/<int:teacher_id>/students/', TeacherStudentsView.as_view(), name='teacher_students'),
    path('api/levels/list/', LevelListView.as_view(), name='level_list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)