# Generated by Django 5.1.2 on 2025-06-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student_qr", "0001_initial"),
        ("teacher_qr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grades",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher_qr.subject"
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grades",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.level"
            ),
        ),
        migrations.AddField(
            model_name="schedules_st",
            name="Teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher_qr.teacher"
            ),
        ),
        migrations.AddField(
            model_name="schedules_st",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schedules_st",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher_qr.classe"
            ),
        ),
        migrations.AddField(
            model_name="schedules_st",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.level"
            ),
        ),
        migrations.AddField(
            model_name="schedules_st",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher_qr.subject"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_qr.schedules_st",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.level"
            ),
        ),
        migrations.AddField(
            model_name="grades",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.student"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.student"
            ),
        ),
        migrations.AddField(
            model_name="admissions",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student_qr.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "schedule", "date")},
        ),
    ]
