# Generated by Django 5.1.2 on 2025-06-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student_qr", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("numero", models.CharField(max_length=15)),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Guardian", "Guardian"),
                            ("Other", "Other"),
                        ],
                        default="Guardian",
                        max_length=20,
                    ),
                ),
                ("is_emergency_contact", models.BooleanField(default=True)),
                ("is_account_created", models.BooleanField(default=False)),
                ("status", models.CharField(default="Inactive", max_length=20)),
                (
                    "temporary_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="student_qr.student"
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="sent", max_length=20)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="parent.parent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="parent",
            constraint=models.UniqueConstraint(
                fields=("mail", "admin"), name="unique_parent_email_per_admin"
            ),
        ),
    ]
