# Generated by Django 5.1.2 on 2025-03-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_parent",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_teacher",
        ),
        migrations.AddField(
            model_name="customuser",
            name="school_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="customuser_set",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="customuser_permissions_set",
                to="auth.permission",
            ),
        ),
    ]
